import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/Navbar";
import Footer from "@/app/Footer";
import Home from "@/app/conponent/Home/Home";
import Contct from "@/app/conponent/Contect/Contct";
import About from "@/app/conponent/About/About";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
       <Navbar/>
       <Home/>
       <Contct/>
       <About/>

        {children}
        <Footer/>
        </body>
    </html>
  );
}
